import AutoImporter from "./AutoImporter.js";
let JSDateProto = {
    getDate: Date.prototype.getDate,
    getDay: Date.prototype.getDay,
    getFullYear: Date.prototype.getFullYear,
    getHours: Date.prototype.getHours,
    getMilliseconds: Date.prototype.getMilliseconds,
    getMinutes: Date.prototype.getMinutes,
    getMonth: Date.prototype.getMonth,
    getSeconds: Date.prototype.getSeconds,
    getTime: Date.prototype.getTime,
    getTimezoneOffset: Date.prototype.getTimezoneOffset,
    getUTCDate: Date.prototype.getUTCDate,
    getUTCDay: Date.prototype.getUTCDay,
    getUTCFullYear: Date.prototype.getUTCFullYear,
    getUTCHours: Date.prototype.getUTCHours,
    getUTCMilliseconds: Date.prototype.getUTCMilliseconds,
    getUTCMinutes: Date.prototype.getUTCMinutes,
    getUTCMonth: Date.prototype.getUTCMonth,
    getUTCSeconds: Date.prototype.getUTCSeconds,
    getYear: Date.prototype.getYear,
    setDate: Date.prototype.setDate,
    setFullYear: Date.prototype.setFullYear,
    setHours: Date.prototype.setHours,
    setMilliseconds: Date.prototype.setMilliseconds,
    setMinutes: Date.prototype.setMinutes,
    setMonth: Date.prototype.setMonth,
    setSeconds: Date.prototype.setSeconds,
    setTime: Date.prototype.setTime,
    setUTCDate: Date.prototype.setUTCDate,
    setUTCFullYear: Date.prototype.setUTCFullYear,
    setUTCHours: Date.prototype.setUTCHours,
    setUTCMilliseconds: Date.prototype.setUTCMilliseconds,
    setUTCMinutes: Date.prototype.setUTCMinutes,
    setUTCMonth: Date.prototype.setUTCMonth,
    setUTCSeconds: Date.prototype.setUTCSeconds,
    setYear: Date.prototype.setYear,
    toDateString: Date.prototype.toDateString,
    toGMTString: Date.prototype.toGMTString,
    toISOString: Date.prototype.toISOString,
    //toJSON: Date.prototype.toJSON,
    toLocaleDateString: Date.prototype.toLocaleDateString,
    toLocaleFormat: Date.prototype.toLocaleFormat,
    toLocaleString: Date.prototype.toLocaleString,
    toLocaleTimeString: Date.prototype.toLocaleTimeString,
    toSource: Date.prototype.toSource,
    toString: Date.prototype.toString,
    toTimeString: Date.prototype.toTimeString,
    toUTCString: Date.prototype.toUTCString,
    valueOf: Date.prototype.valueOf
}

export default Object.assign(
    AutoImporter.importer("Date", JSDateProto, 1, undefined, undefined, true), {
        Date: AutoImporter.generator(Date, "Date", "Date", false),
        UTC: AutoImporter.generator(Date.UTC, "Date", "UTC", false),
        now: AutoImporter.generator(Date.now, "Date", "now", false),
        parse: AutoImporter.generator(Date.parse, "Date", "parse", false)
    }
);